- Packages and Modules using OOP'S
    - Similar to packages and modules in python,but here dealing with objects and class
    - package(Folder) - Collection modules
    - Module(.py file) - collection of functions and classes
    - Accessing modules using import keyword
        - from foldername import file(.py)

In [1]:
from package import Oops

In [7]:
print(dir(Oops))

['Mymath', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']


In [3]:
obj = Oops.Mymath(9,9)
print(obj.add())

18


In [4]:
from package.Oops import Mymath

In [6]:
print(dir(Mymath))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add']


In [8]:
from package.Oops2 import Modu

In [9]:
print(dir(Modu))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'isEven', 'power']


In [12]:
ob = Modu
print(ob.power(2,5))

32


In [13]:
print(ob.isEven(7))

False


In [2]:
from package.Oops import demo

In [5]:
ob = demo
#print(ob.a)
(ob.add())
(ob.sub())

16
2


- Data Science
    - Organising,Processing and analysing huge amount of data
    - Invloves different disciplines like mathematical and statistical modelling
    - Extracting data from source
    - apply for data visualization
    - nearly 20 python libraries for data science
        - scipy
        - tensorflow
        - Numpy
        - pandas
        - Matplotlib

- Numpy
    - Numerical Python
    - Fundamental Package for scientific computing
    - python library provides multidimensional array object
- Installation
    - pip install numpy(windows)
    - sudo apt-get install python3 numpy

In [6]:
import numpy as np
np.__version__

'1.15.4'

In [7]:
np?

In [8]:
# creating an array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
np.array([1,2,3,5.7])

array([1. , 2. , 3. , 5.7])

In [11]:
np.array([1,2,3,4],dtype='int')

array([1, 2, 3, 4])

In [13]:
np.array([1,2,3,5.7],dtype='int')

array([1, 2, 3, 5])

In [14]:
np.array([ range(i,i+3) for i in [2,4,6]])
# (2,5)
# (4,7)
# (6,9)
# 2 3 4
# 4 5 6
# 6 7 8 

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
print(dir(np.dtype))

['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'alignment', 'base', 'byteorder', 'char', 'descr', 'fields', 'flags', 'hasobject', 'isalignedstruct', 'isbuiltin', 'isnative', 'itemsize', 'kind', 'metadata', 'name', 'names', 'ndim', 'newbyteorder', 'num', 'shape', 'str', 'subdtype', 'type']


In [18]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [19]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
# ndim() -- No. of dimensions of an array
a.ndim

1

In [21]:
a.dtype

dtype('int32')

In [22]:
# shape in tuple format
a.shape

(6,)

In [23]:
# Number of elements
a.size

6

In [24]:
# returns each item size in bytes
a.itemsize

4

In [25]:
# U11 -- Unicode String of max length 11
b = np.array([100,78,56,'python'])
b

array(['100', '78', '56', 'python'], dtype='<U11')

In [26]:
c = np.array([1,5,7])
c = np.append(c,'A')
c

array(['1', '5', '7', 'A'], dtype='<U11')

In [27]:
c = np.append(c,[2,4,6,8])
c

array(['1', '5', '7', 'A', '2', '4', '6', '8'], dtype='<U11')

In [28]:
# creating ndarray using range()
# range(startvalue,endvalue,stepvalue)
r = np.array(range(1,9,2))
print(r)
print(type(r))

[1 3 5 7]
<class 'numpy.ndarray'>


In [29]:
# create an array with linear sequence
# similar to built-in range() function
a = np.arange(1,11)
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [30]:
#nbytes -- checking memory space occupied by an array
a.nbytes

40

In [31]:
print(a.itemsize) # checking each element size

4


In [32]:
print(len(a))

10


In [33]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.full((2,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [38]:
# linspace -- create an array with evenly spaced betwen ranges
h = np.linspace(0,1,5)
h

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [49]:
k = np.linspace(2,7,8)
k

array([2.        , 2.71428571, 3.42857143, 4.14285714, 4.85714286,
       5.57142857, 6.28571429, 7.        ])

In [39]:
data = np.random.randint(1,20)
data

4

In [44]:
data = np.random.randint(1,20,size=(9,10))
data

array([[17, 15, 16, 16, 15,  3,  1, 12,  6, 16],
       [14, 10, 15,  5,  5, 18, 15,  3, 13, 12],
       [ 7, 15,  3, 19, 15,  9, 10, 18,  8, 13],
       [16,  3, 13,  9,  3, 12, 13, 17, 11,  4],
       [12, 12,  2,  7, 13, 10, 16,  9,  3,  2],
       [11,  6,  5, 12, 14, 11, 11, 10,  3, 15],
       [11, 13,  5, 17, 15,  7, 18, 12,  5, 12],
       [14,  6,  9, 17,  7, 13,  1,  4,  3, 19],
       [17, 19, 16,  4, 13,  8, 10,  6, 14, 13]])

In [48]:
x = np.arange(10).reshape((5,2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])