- Numpy Continution
    - Accessing elements from an array

In [1]:
import numpy as np

In [3]:
a = np.array([10,20,20,4,6])
a

array([10, 20, 20,  4,  6])

In [4]:
a[3]

4

In [5]:
a[-5]

10

In [6]:
a[1:4]

array([20, 20,  4])

In [7]:
a[::-1]

array([ 6,  4, 20, 20, 10])

In [8]:
# 2-D Array
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
b.size

8

In [10]:
b.shape

(2, 4)

In [11]:
# 1st row elements
b[0]

array([1, 2, 3, 4])

In [12]:
# 2nd row elements
b[1]

array([5, 6, 7, 8])

In [14]:
# Accessing particular element in a row
b[0][1]

2

In [15]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
# Accessing particular element in row and column
b[1,1]

6

In [17]:
# Accessing a particular column
b[:,0]

array([1, 5])

In [18]:
b[:,1]

array([2, 6])

In [20]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
# row index slicing,element index slicing
b[:,-2:]

array([[3, 4],
       [7, 8]])

In [22]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

In [23]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [25]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [26]:
a.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [27]:
a.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [28]:
a = np.array([100,20,90,89,78,76])
a

array([100,  20,  90,  89,  78,  76])

In [30]:
for i in a:
    print(i,end=' ')

100 20 90 89 78 76 

In [31]:
# 2D Array
b = a.reshape(2,3)
b

array([[100,  20,  90],
       [ 89,  78,  76]])

In [32]:
# 100 20 90 -- 100,20,90
# 89 78 76 -- 89 78 76
for i in b:
    for j in i:
        print(j,end=' ')

100 20 90 89 78 76 

In [34]:
a

array([100,  20,  90,  89,  78,  76])

In [33]:
# # 3-D Array
c = a.reshape(2,3,1)
c

array([[[100],
        [ 20],
        [ 90]],

       [[ 89],
        [ 78],
        [ 76]]])

In [35]:
for i in c:
    for j in i:
        for k in j:
            print(k,end=' ')

100 20 90 89 78 76 

In [38]:
for i in c:
    for j in i:
        for k in j:
            print(k,end=' ')

100 20 90 89 78 76 

In [40]:
b

array([[100,  20,  90],
       [ 89,  78,  76]])

In [39]:
for i in np.nditer(b):
    print(i,end=' ')

100 20 90 89 78 76 

In [42]:
#help(np.nditer)

- Joining of Array
    - Concatinate

In [44]:
a = np.arange(1,5)
b = np.arange(11,20)
print(a,end=' ')
print(b,end=' ')

[1 2 3 4] [11 12 13 14 15 16 17 18 19] 

In [45]:
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
a = np.arange(1,5)
b = np.arange(6,10)
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [47]:
c = a.reshape(2,2)
d = b.reshape(2,2)
print(c)
print(d)
e = np.concatenate((c,d))
e

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

- Statistical And Math Operations

In [48]:
c

array([[1, 2],
       [3, 4]])

In [50]:
np.min(c)

1

In [51]:
np.max(c)

4

In [52]:
# returns the index of minimum value of an array
c.argmin()

0

In [53]:
c.argmax()

3

In [54]:
help(c.argmin)

Help on built-in function argmin:

argmin(...) method of numpy.ndarray instance
    a.argmin(axis=None, out=None)
    
    Return indices of the minimum values along the given axis of `a`.
    
    Refer to `numpy.argmin` for detailed documentation.
    
    See Also
    --------
    numpy.argmin : equivalent function



In [55]:
c

array([[1, 2],
       [3, 4]])

In [57]:
print(np.mean(c))
print(np.median(c))
print(np.var(c))
print(np.average(c))
print(np.std(c))

2.5
2.5
1.25
2.5
1.118033988749895


- Stacking
    - Arraging / organising in an appropriate way
    - Horizontal Stacking
    - Vertical Stacking

In [58]:
c

array([[1, 2],
       [3, 4]])

In [59]:
np.hstack(c)

array([1, 2, 3, 4])

In [60]:
h = np.array([1,2,3,4])
h

array([1, 2, 3, 4])

In [61]:
np.vstack(h)

array([[1],
       [2],
       [3],
       [4]])

In [62]:
c

array([[1, 2],
       [3, 4]])

In [63]:
print(np.sqrt(c))
print(np.exp(c))
print(np.sin(c))
print(np.log(c))
print(np.log2(c))
print(np.log10(c))
print(np.power(c,3))
print(np.remainder(c,3))
print(np.degrees(c))
print(np.diff(c))
print(np.diff(c,axis=0))
print(np.multiply(c,100))
print(np.divide(c,2))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[0.         0.69314718]
 [1.09861229 1.38629436]]
[[0.        1.       ]
 [1.5849625 2.       ]]
[[0.         0.30103   ]
 [0.47712125 0.60205999]]
[[ 1  8]
 [27 64]]
[[1 2]
 [0 1]]
[[ 57.29577951 114.59155903]
 [171.88733854 229.18311805]]
[[1]
 [1]]
[[2 2]]
[[100 200]
 [300 400]]
[[0.5 1. ]
 [1.5 2. ]]


In [65]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [66]:
a = np.array([1+2j,9+4j,8+5j])
a

array([1.+2.j, 9.+4.j, 8.+5.j])

In [67]:
np.real(a)

array([1., 9., 8.])

In [68]:
np.imag(a)

array([2., 4., 5.])

In [69]:
l = [1,2,3,4]
k = l
print(l)
print(k)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [70]:
l.append('z')
print(l)
print(k)

[1, 2, 3, 4, 'z']
[1, 2, 3, 4, 'z']


In [71]:
l = [1,2,3,4]
k = l.copy()
print(l)
print(k)

[1, 2, 3, 4]
[1, 2, 3, 4]


In [72]:
l.pop()
print(l)
print(k)

[1, 2, 3]
[1, 2, 3, 4]


- Ravel and Flatten
    - Ravel 
        - used to create copy of original array, when any changes made in duplicate array those will be applied in original also
    - Flatten
        -  - used to create copy of original array, when any changes made in duplicate array those will not be applied in original also

In [74]:
org = np.arange(1,10)
org

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
copy = org.ravel()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
copy[0] = 100
copy

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [77]:
org

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [78]:
dup = org.flatten()
dup

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [79]:
org

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [81]:
dup[1]=0
dup

array([100,   0,   3,   4,   5,   6,   7,   8,   9])

In [82]:
org

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

- Numpy Structured Arrays

In [2]:
name = ['A','B','C','D']
age = [25,45,37,19]
weight = [55.0,85.5,68.0,61.5]

In [3]:
x = np.zeros(4,dtype=int)
x

array([0, 0, 0, 0])

In [4]:
data = np.zeros(4,dtype={'names':('name','age','weight'),
                        'formats':('U10','i4','f8')})
print(data.dtype)
#print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [5]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('A', 25, 55. ) ('B', 45, 85.5) ('C', 37, 68. ) ('D', 19, 61.5)]


In [6]:
# Get all names
data['name']

array(['A', 'B', 'C', 'D'], dtype='<U10')

In [7]:
data[0]

('A', 25, 55.)

In [8]:
data[-1]

('D', 19, 61.5)

In [10]:
data

array([('A', 25, 55. ), ('B', 45, 85.5), ('C', 37, 68. ), ('D', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [11]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['A', 'D'], dtype='<U10')